apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  labels:
    app: my-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
        app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers: 
        - name: app
          image: gabriel8819/myapp
          ports:
             - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  type: NodePort
  selector:
    app: nginx
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000


